[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
jup_agg_proxy = "5fNnwbi4LvpjYgoYBsgs6kdKb1h16vH8ZwZvM73sV79Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
