[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
arbitrage = "4mhXfgu8vPvWfqTMPb9rPFJS23bQB2XZBZekmAfKt9YC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
